### ISSUE TITLE
Can't compile because of no matching function for call to 'evdi_enable_cursor_events'

### ISSUE THREAD

**Issue by KhazAkar** [mlukaszek/evdipp#4]
Hi, I'd want to test you application out, but I cannot finish compilation of it.
openSUSE Tumbleweed, recently updated, evdi 1.9.1 installed on the system.
Any ideas?

> [  9%] Performing update step for 'github_evdi'
> [  9%] Building CXX object libevdipp/CMakeFiles/evdipp.dir/buffer.cpp.o
> [ 19%] Building CXX object libevdipp/CMakeFiles/evdipp.dir/screen.cpp.o
> [ 19%] Building CXX object libevdipp/CMakeFiles/evdipp.dir/evdi.cpp.o
> /home/khazakar/downloadedwithgit/evdipp/libevdipp/evdi.cpp:56:5: error: no matching function for call to 'evdi_enable_cursor_events'
>     evdi_enable_cursor_events(handle);
>     ^~~~~~~~~~~~~~~~~~~~~~~~~
> /home/khazakar/downloadedwithgit/evdipp/github_evdi-prefix/src/github_evdi/library/evdi_lib.h:112:6: note: candidate function not viable: requires 2 arguments, but 1 was provided
> void evdi_enable_cursor_events(evdi_handle handle, bool enable);
>      ^
> 1 error generated.
> make[2]: *** [libevdipp/CMakeFiles/evdipp.dir/build.make:95: libevdipp/CMakeFiles/evdipp.dir/evdi.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> [ 23%] No patch step for 'github_evdi'
> [ 28%] No configure step for 'github_evdi'
> [ 33%] Performing build step for 'github_evdi'
> [ 38%] No install step for 'github_evdi'
> [ 42%] Completed 'github_evdi'
> [ 52%] Built target github_evdi
> make[1]: *** [CMakeFiles/Makefile2:185: libevdipp/CMakeFiles/evdipp.dir/all] Error 2
> make: *** [Makefile:149: all] Error 2

**Comment by Eddie-064** [comment]
you can just change the 56 line in libevdipp/evdi.cpp file 
from evdi_enable_cursor_events(handle); to evdi_enable_cursor_events(handle, true );

**Comment by mlukaszek** [comment]
This should be now resolved with cda666e
